[versions]
detekt = "1.23.8"
spring-boot-v3 = "3.5.7"

[libraries]
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-libraries = { group = "io.gitlab.arturbosch.detekt", name = "detekt-rules-libraries", version.ref = "detekt" }
spring-boot-v3-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot-v3" }
springdoc-openapi = "org.springdoc:springdoc-openapi-bom:2.8.14"
spring-cloud = "org.springframework.cloud:spring-cloud-dependencies:2025.1.1"
datasource-micrometer = "net.ttddyy.observation:datasource-micrometer-spring-boot:1.2.0"
logstash = "net.logstash.logback:logstash-logback-encoder:8.1"

[plugins]
spring-boot-v3 = { id = "org.springframework.boot", version.ref = "spring-boot-v3" }
